// Code generated by migrator-file-manager. DO NOT EDIT.
// Package migrations describes database migrations.
package migrations

import (
	migrator "github.com/sulimak-co/gorm-migrator"
)

func GetMigrationsList() []migrator.Migration {
	return []migrator.Migration{
		{
			Up:   createOrganizationTableUp,
			Down: createOrganizationTableDown,
		},
		{
			Up:   createUserTableUp,
			Down: createUserTableDown,
		},
	}
}
