package main

var (
	migrationTemplate = `package migrations

import (
	"gorm.io/gorm"
)

func {{.MigrationName}}Up(migrator gorm.Migrator) error {

	return nil
}

func {{.MigrationName}}Down(migrator gorm.Migrator) error {

	return nil
}
`
	migrationListTemplate = `// Code generated by migrator-file-manager. DO NOT EDIT.
// Package migrations describes database migrations.
package migrations

import (
	migrator "github.com/sulimak-co/gorm-migrator"
)

func GetMigrationsList() []migrator.Migration {
	return []migrator.Migration{
{{.Items}}
	}
}
`
	migrationListItemTemplate = `		{
			Up:   {{.MigrationName}}Up,
			Down: {{.MigrationName}}Down,
		},`
)
